### PR TITLE
Add `locked` and `frozen` flags to CargoExtension

### PR DESCRIPTION
**Pull request by thomcc**

### CODE REVIEW

**Comment by thomcc** [comment]
Actually, this would probably be better as just an arbitrary argument array. Would save a lot of churn since this certainly doesn't have all the things cargo allows you to pass (e.g. we wanted to add `default-members` to our workspace before, but that broke rust android gradle since it doesn't pass -p specifying the package to build)

**Comment by ncalexan** [comment]
> Actually, this would probably be better as just an arbitrary argument array. Would save a lot of churn since this certainly doesn't have all the things cargo allows you to pass (e.g. we wanted to add `default-members` to our workspace before, but that broke rust android gradle since it doesn't pass -p specifying the package to build)

I'm happy to take something like `cargoBuildArguments` if you'd prefer that, @thomcc.  No sense being ideologically pure here: it's obvious that we need escape hatches in the wild.

We're specifying the path to the TOML file, IIRC.  Is it better to use `-p`, for workspace reasons?

**Comment by thomcc** [comment]
> We're specifying the path to the TOML file, IIRC. Is it better to use -p, for workspace reasons?

Yes, if the crate specifies default-members for the workspace (which we'd like to since there's no point in building all the megazords for most `cargo build` or `cargo test` invocations from the root), then without the -p, only the default members of that crate will be built, no matter where in the workspace the command is issued, unless `-p` (or `--all`) is specified.

**Comment by thomcc** [comment]
Closing in favor of 6

**Pull request closed without merging**
